In [1]:
import numpy as np
#used for numeric data only

In [6]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
#slice first two rows and columns from index 1 to end
print(mat[:2,1:]) #[[2,3] [5,6]] 
print(mat[:,1]) #[2,5,8]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 5 8]


In [16]:
import pandas as pd
#used for all types of data (comination of string,num,image,video)
#allows to do operation on data set

In [18]:
dataset = {'student':['abc','def','hij'],
        'admissions':[2023,2033,2021]}
print(dataset)
demo = pd.DataFrame(dataset)#to print data in proper format like rows and columns
print(demo)

{'student': ['abc', 'def', 'hij'], 'admissions': [2023, 2033, 2021]}
  student  admissions
0     abc        2023
1     def        2033
2     hij        2021


In [11]:
pd.__version__ #checks the version of pandas

'0.23.4'

In [19]:
a = [20,30,40,50]
demo1 = pd.Series(a) # print data one dim labeled array line by line
print(demo1)

0    20
1    30
2    40
3    50
dtype: int64


In [20]:
demo2 = pd.Series(a,index=['m1','m2','m3','m4'])
print(demo2)

m1    20
m2    30
m3    40
m4    50
dtype: int64


In [27]:
marks = {'a':200,'b':900,'c':344}
print(marks)
m = pd.Series(marks)
print(m)

{'a': 200, 'b': 900, 'c': 344}
a    200
b    900
c    344
dtype: int64


In [46]:
print(m[1])#index no
print(m['c'])#label
print(m.iloc[0])# index location function()

900
344
200


In [45]:
data = {'product':["kurkure","milk","cheese","paneer","ice creame"],"price":[10,30,125,45,110]}
datafr = pd.DataFrame(data)
print(datafr)
print("\n\n")
print(datafr.iloc[2])
print("\n\n")
print(datafr.loc[4])

      product  price
0     kurkure     10
1        milk     30
2      cheese    125
3      paneer     45
4  ice creame    110



product    cheese
price         125
Name: 2, dtype: object



product    ice creame
price             110
Name: 4, dtype: object


In [54]:
d = [['a',20],['b',30],['c',40],['d',50]]
df = pd.DataFrame(d,columns=['Name',"Age"])
print(df)

  Name  Age
0    a   20
1    b   30
2    c   40
3    d   50
